version: '2.1'

services:

  demo-db:
    image: --
    # healthcheck:
    #   #test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 45s
    #   interval: 10s
    #   retries: 5
    restart: always
    environment:
      MYSQL_DATABASE: 'online-platform'
      # MYSQL_USER: ''
      # MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    container_name: demo-db

  demo-be:
    image: --
    restart: always
    ports:
      - "8080:8080"
    environment:
      #- DB_IP=172.22.0.2
      - MYSQL_IP=demo-db
      - MYSQL_PORT=3306
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DBNAME=online-platform
    depends_on:
      - demo-db
        # condition: service_healthy
